django_project/blog/urls.py
from django.urls import path
from . import views


app_name = 'taller'

urlpatterns = [
	path('', views.inicio, name='tallerInicio'),
	path('registro', views.registro, name='tallerRegistro'),
	path('programa', views.programa, name='tallerPrograma'),
	path('talleres', views.talleres, name='tallerTalleres'),
	path('success/<str:tipoExito>', views.exito, name='tallerExito'),
	path('warning/<int:i>-<int:t>/<int:bandera>', views.warning, name='tallerWarning'),
	path('inscripcion/<int:idTaller>', views.inscripcion, name='tallerInscripcion'),

	path('manage', views.administradorInicio, name="administradorInicio"),

	path('manage/general', views.ViewGeneral.as_view(), name="administradorGeneral"),
	path('manage/editarGeneral/<int:idElemento>', views.editarGeneral, name="editarGeneral"),

	path('manage/participantes', views.ViewParticipantes.as_view(), name="administradorParticipantes"),
	path('manage/participantesMondragon', views.participantesMondragon, name="administradorParticipantesMondragon"),
	path('manage/editarParticipante/<int:idElemento>', views.editarParticipante, name="editarParticipante"),
	path('manage/nuevoParticipante', views.nuevoParticipante, name="nuevoParticipante"),
	path('manage/eliminarParticipante/<int:idElemento>', views.eliminarParticipante, name="eliminarParticipante"),

	path('manage/programa', views.ViewPrograma.as_view(), name="administradorPrograma"),
	path('manage/editarPrograma/<int:idElemento>', views.editarPrograma, name="editarPrograma"),
	path('manage/nuevoPrograma', views.nuevoPrograma, name="nuevoPrograma"),
	path('manage/eliminarPrograma/<int:idElemento>', views.eliminarPrograma, name="eliminarPrograma"),

	path('manage/talleres', views.ViewTalleres.as_view(), name="administradorTalleres"),
	path('manage/editarTaller/<int:idElemento>', views.editarTaller, name="editarTaller"),
	path('manage/nuevoTaller', views.nuevoTaller, name="nuevoTaller"),
	path('manage/eliminarTaller/<int:idElemento>', views.eliminarTaller, name="eliminarTaller"),
	
	path('manage/inscripciones', views.ViewInscripciones.as_view(), name="administradorInscripciones"),
	path('manage/editarInscripcion/<int:idElemento>', views.editarInscripcion, name="editarInscripcion"),
	path('manage/nuevoInscripcion', views.nuevoInscripcion, name="nuevoInscripcion"),
	path('manage/eliminarInscripcion/<int:idElemento>', views.eliminarInscripcion, name="eliminarInscripcion"),
]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('blog.urls')),
    path(r'',include('blog.urls'),name='blog-index'),
]

django_project/blog/models.py
from django.db import models

CHOICES = [
			('sí', 'Sí'),
			('no', 'No'),			
		]

class Participante(models.Model):
	nombre = models.CharField(max_length=100)
	apellidoPaterno = models.CharField(max_length=100)
	apellidoMaterno = models.CharField(max_length=100)
	correo = models.EmailField(max_length=100)
	institucion = models.CharField(max_length=200)
	mondragon = models.CharField(choices=CHOICES, max_length=2)
	#date_posted = models.DateTimeField(default=timezone.now)

class Detalle(models.Model):
	lugar = models.CharField(max_length=100)
	fecha = models.CharField(max_length=100)
	hora = models.CharField(max_length=50)
	direccion = models.CharField(max_length=150)
	telefono = models.CharField(max_length=20)
	telefono2 = models.CharField(max_length=20)
	correo = models.EmailField(max_length=100)
	cupoMax = models.IntegerField()
	#descripcion = models.TextField()

class Taller(models.Model):
	dia = models.CharField(max_length=50)
	horario = models.CharField(max_length=50)
	nombre = models.CharField(max_length=200)
	ponente = models.CharField(max_length=100)
	cupo = models.IntegerField()

class Programa(models.Model):
	dia = models.CharField(max_length=50)
	horario = models.CharField(max_length=50)
	actividad = models.CharField(max_length=200)

class Inscripcion(models.Model):
	idTaller = models.ForeignKey(Taller, null=True, blank=True, on_delete=models.CASCADE)
	taller = models.CharField(max_length=200)
	dia = models.CharField(max_length=50)
	horario = models.CharField(max_length=50)
	idParticipante = models.ForeignKey(Participante, null=True, blank=True, on_delete=models.CASCADE)
	nombre = models.CharField(max_length=100)
	apellidoPaterno = models.CharField(max_length=100)
	apellidoMaterno = models.CharField(max_length=100)

django_project/blog/forms.py
from django import forms
from .models import Participante, Inscripcion, Taller, Detalle, Programa

class ParticipanteForm(forms.ModelForm):
	class Meta:
		model = Participante
		fields = (
			'nombre',
			'apellidoPaterno',
			'apellidoMaterno',
			'correo',
			'institucion',
			'mondragon',
		)

		labels = {
			'apellidoPaterno': 'Apellido Paterno:',
			'apellidoMaterno': 'Apellido Materno:',
			'mondragon': '¿Eres estudiante o docente de la Universidad Mondragón?',
		}


class InscripcionForm(forms.ModelForm):
	class Meta:
		model = Inscripcion

		fields = (
				'nombre',
				'apellidoPaterno',
				'apellidoMaterno',
			)

		labels = {
			'apellidoPaterno': 'Apellido Paterno:',
			'apellidoMaterno': 'Apellido Materno:',
		}

class AdminGeneralForm(forms.ModelForm):
	class Meta:
		model = Detalle

		fields = (
				'lugar',
				'fecha',
				'hora',
				'direccion',
				'telefono',
				'telefono2',
				'correo',
				'cupoMax'
			)

class AdminInscripcionesForm(forms.ModelForm):
	class Meta:
		model = Inscripcion
		fields = (
				'taller',
				'dia',
				'horario',
				'nombre',
				'apellidoPaterno',
				'apellidoMaterno',
			)

class AdminTalleresForm(forms.ModelForm):
	class Meta:
		model =Taller

		fields = (
				'dia',
				'horario',
				'nombre',
				'ponente',
				'cupo',
			)
class AdminProgramaForm(forms.ModelForm):
	class Meta:
		model = Programa

		fields = (
				'dia',
				'horario',
				'actividad'
			)

django_project/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Participante, Detalle, Programa, Taller, Inscripcion
from .forms import ParticipanteForm, InscripcionForm, AdminGeneralForm, AdminTalleresForm, AdminProgramaForm, AdminInscripcionesForm
from django.views.generic import ListView
from django.contrib import messages

def inicio(request):
	contexto = {
		'detalles': Detalle.objects.first(),
	}
	return render(request, 'blog/inicio.html', contexto)		

def registro(request):
	if request.method == 'POST':
		form = ParticipanteForm(request.POST)
		if form.is_valid():
			data = request.POST.copy()
			n = data.get('nombre')
			aP = data.get('apellidoPaterno')
			aM = data.get('apellidoMaterno')
			c = data.get('correo')
			existenciaParticipante = Participante.objects.filter(nombre=n,apellidoPaterno=aP, apellidoMaterno=aM, correo=c)
			if(existenciaParticipante):
				messages.error(request, 'Ya estás registrado')
			else:
				form.save()
				messages.success(request, 'Registro exitoso')
			form = ParticipanteForm()
			#return redirect('taller:tallerExito', "r")
	else:
		form = ParticipanteForm()
	return render(request, 'blog/registro.html', {'title':'Registro', 'form': form})

def exito(request, tipoExito):
	if tipoExito != 'r' and tipoExito != 'i':
		return redirect('taller:tallerInicio')	
	return render(request, 'blog/exito.html',{'title':'Success','tipoExito': tipoExito})	


def talleres(request):
	detalles = {
		'title': 'Talleres',
		'jueves1': Taller.objects.filter(dia='jueves', horario='12:00 - 14:30'),
		'jueves2': Taller.objects.filter(dia='jueves', horario='17:10 - 19:30'),
		'viernes': Taller.objects.filter(dia='viernes', horario='11:00 - 13:30'),
	}
	return render(request, 'blog/talleres.html', detalles)

def programa(request):
	detalles = {
		'request':request,
		'jueves': Programa.objects.filter(dia='jueves').order_by('horario'),
		'viernes': Programa.objects.filter(dia='viernes').order_by('horario'),
		'title':'Programa',
	}
	return render(request, 'blog/programa.html', detalles )

def warning(request, i, t, bandera):
	inscripcion = Inscripcion.objects.get(id=i)
	viejoT = Taller.objects.get(id=inscripcion.idTaller.id)
	if bandera == 1:
		taller = Taller.objects.get(id=t)
		inscripcion.taller = taller.nombre
		inscripcion.save()
		taller.inscripcion_set.add(inscripcion)
		taller.cupo = taller.cupo-1
		taller.save()
		viejoT.cupo = viejoT.cupo+1
		viejoT.save()
		messages.success(request, 'Cambios guardados exitosamente')
		detalles = {
			'title':'Programa',
			'i': i,
			't': t,
		}
	else:
		detalles = {
			'title':'Programa',
			'i': i,
			't': t,
			'taller': inscripcion.taller,
		}
	return render(request, 'blog/warning.html',detalles)	


def inscripcion(request, idTaller):
	#taller = Taller.objects.get(id=idTaller)
	taller = get_object_or_404(Taller, id=idTaller)
	details = Detalle.objects.get(id=1)
	cupoMax = details.cupoMax
	if request.method == 'GET':
		form = InscripcionForm()
		detalles = {
			'title': 'Inscripción',
			'taller': taller,
			'form': form,
		}
	if request.method == 'POST':
		form = InscripcionForm(request.POST)
		if form.is_valid():
			if(taller.cupo>0 and taller.cupo<=cupoMax):
				data = request.POST.copy()
				n = data.get('nombre')
				aP = data.get('apellidoPaterno')
				aM = data.get('apellidoMaterno')
				existenciaParticipante = Participante.objects.filter(nombre=n,apellidoPaterno=aP, apellidoMaterno=aM)
				if(existenciaParticipante):
					
					inscritoTaller = Inscripcion.objects.filter(taller=taller.nombre, nombre=n,apellidoPaterno=aP, apellidoMaterno=aM)
					if(inscritoTaller):
						messages.error(request, 'Ya estás registrado en este taller')
						#Ya está registrado en este taller
					else:
						inscrito = Inscripcion.objects.filter(horario=taller.horario,nombre=n,apellidoPaterno=aP, apellidoMaterno=aM)
						p = Participante.objects.get(nombre=n,apellidoPaterno=aP, apellidoMaterno=aM)
						if(inscrito):
							#i = Inscripcion.objects.get(horario=taller.horario,nombre=n,apellidoPaterno=aP, apellidoMaterno=aM)
							i = Inscripcion.objects.get(horario=taller.horario,nombre=n,apellidoPaterno=aP, apellidoMaterno=aM)
							return redirect('taller:tallerWarning', i.id, taller.id, 0)
							#Ya estás registrado en un taller del mismo horario
						else:
							nuevaI = Inscripcion(taller=taller.nombre, dia=taller.dia, horario=taller.horario,nombre=n, apellidoPaterno=aP, apellidoMaterno=aM)
							nuevaI.save()
							taller.inscripcion_set.add(nuevaI)
							p.inscripcion_set.add(nuevaI)
							taller.cupo = taller.cupo-1
							taller.save()
							messages.success(request, 'Inscripción exitosa')
							#Inscripción exitosa
				else:
					messages.error(request, 'Todavía no estás registrado')
					#return HttpResponse(detalles['validacion'])
					#messages.warning(request, detalles['participante'].nombre)
					#Usuario no existe
			else:
				messages.error(request, 'Ya no hay cupo para este taller')
				#Cupo límite
			return redirect('taller:tallerInscripcion', idTaller)
	return render(request, 'blog/inscripcion.html', detalles)


#Páginas administrador

def administradorInicio(request):
	return render(request, 'admin/inicio.html')

class ViewGeneral(ListView):
	model = Detalle
	template_name = 'admin/general.html'
	detalles = {
	'title': 'General Admin',
	}

def editarGeneral(request, idElemento):
	elemento = Detalle.objects.get(id = idElemento)
	if request.method == 'GET':
		form = AdminGeneralForm(instance=elemento)
	else:
		form = AdminGeneralForm(request.POST, instance=elemento)
		if form.is_valid():
			form.save()
		return redirect('taller:administradorGeneral')
	return render(request, 'admin/generalForm.html', {'form':form})

class ViewParticipantes(ListView):
	model = Participante
	queryset = Participante.objects.order_by('apellidoPaterno','apellidoMaterno','nombre')
	template_name = 'admin/participantes.html'
	detalles = {
		'title': 'Participantes Admin',
	}

def participantesMondragon(request):
	contexto = {
		'participantes': Participante.objects.filter(mondragon = 'sí'),
		'title': 'Participantes Mondragón',
	}
	return render(request, 'admin/participantesMondragon.html', contexto)	

def nuevoParticipante(request):
	if request.method == 'POST':
		form = ParticipanteForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('taller:administradorParticipantes')
	else:
		form = ParticipanteForm()
	return render(request, 'admin/participantesForm.html', {'form':form})

def eliminarParticipante(request, idElemento):
	elemento = Participante.objects.get(id=idElemento)
	if(request.method == 'GET'):
		elemento.delete()
		return redirect('taller:administradorParticipantes')

def editarParticipante(request, idElemento):
	elemento = Participante.objects.get(id = idElemento)
	if request.method == 'GET':
		form = ParticipanteForm(instance=elemento)
	else:
		form = ParticipanteForm(request.POST, instance=elemento)
		if form.is_valid():
			form.save()
		return redirect('taller:administradorParticipantes')
	return render(request, 'admin/participantesForm.html', {'form':form})

class ViewPrograma(ListView):
	model = Programa
	queryset = Programa.objects.order_by('dia','horario')
	template_name = 'admin/programa.html'
	detalles = {
		'title': 'Programa Admin',
	}

def nuevoPrograma(request):
	if request.method == 'POST':
		form = AdminProgramaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('taller:administradorPrograma')
		messages.success(request, 'Exito')
	else:
		form = AdminProgramaForm()
	return render(request, 'admin/participantesForm.html', {'form':form})

def eliminarPrograma(request, idElemento):
	elemento = Programa.objects.get(id = idElemento)
	if(request.method == 'GET'):
		elemento.delete()
		return redirect('taller:administradorPrograma')


def editarPrograma(request, idElemento):
	elemento = Programa.objects.get(id = idElemento)
	if request.method == 'GET':
		form = AdminProgramaForm(instance=elemento)
	else:
		form = AdminProgramaForm(request.POST, instance=elemento)
		if form.is_valid():
			form.save()
		return redirect('taller:administradorPrograma')
	return render(request, 'admin/programaForm.html', {'form':form})

class ViewTalleres(ListView):
	model = Taller
	queryset = Taller.objects.order_by('dia','horario','nombre')
	template_name = 'admin/talleres.html'
	detalles = {
		'title': 'Talleres Admin',
	}

def talleresAdmin(request):
	talleres = Taller.objects.all()
	detalles = {
		'talleres': talleres,
		'title': 'Talleres Admin',
	}
	return render(request, 'admin/talleres.html', detalles)


def nuevoTaller(request):
	if request.method == 'POST':
		form = AdminTalleresForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('taller:administradorTalleres')
		messages.success(request, 'Exito')
	else:
		form = AdminTalleresForm()
	return render(request, 'admin/talleresForm.html', {'form':form})

def eliminarTaller(request, idElemento):
	elemento = Taller.objects.get(id = idElemento)
	if(request.method == 'GET'):
		elemento.delete()
		return redirect('taller:administradorTalleres')

def editarTaller(request, idElemento):
	elemento = Taller.objects.get(id = idElemento)
	if request.method == 'GET':
		form = AdminTalleresForm(instance=elemento)
	else:
		form = AdminTalleresForm(request.POST, instance=elemento)
		if form.is_valid():
			form.save()
		return redirect('taller:administradorTalleres')
	return render(request, 'admin/talleresForm.html', {'form':form})

class ViewInscripciones(ListView):
	model = Inscripcion
	queryset = Inscripcion.objects.order_by('dia','horario', 'taller', 'apellidoPaterno','apellidoMaterno','nombre')

django_project/blog/templates/blog/inicio.html
{% extends 'base/index.html '%}
{% load static %}
{% block estilos %}
<link rel="stylesheet" type="text/css" href="{% static 'css/inicio.css' %}">
{% endblock %}

{% block contenido %}

<div class="contenedor">
	<section class="intro">
		<img src="{% static 'img/fondo.png' %}">
	</section>
	
	<section class="registrate">
		<h1>REGISTRO</h1>
		<label>¿Ya estás registrado?</label>
		<p>Regístrate para unirte a la experiencia "Detrás de tu trastorno"</p>
		<a href="{% url 'taller:tallerRegistro' %}">Regístrate</a>
	</section>

	<section class="detalles">
		<div class="detalles-texto">
			<h2>DETALLES EVENTO</h2>
			<div class="detalles-datos">
				<div class="detalles-dato">
					<label>Lugar: </label>
					<p>{{ detalles.lugar }}</p>
				</div>
				<div class="detalles-dato">
					<label>Fecha: </label>
					<p>{{ detalles.fecha }}</p>
				</div>
				<div class="detalles-dato">
					<label>Hora: </label>
					<p>{{ detalles.hora }}</p>
				</div>
				<div class="detalles-dato">
					<label>Dirección: </label>
					<p>{{ detalles.direccion }}</p>
				</div>
			</div>
		</div>
	</section>

	<section class="contacto">
		<div class="contacto-texto">
			<h3>CONTACTO</h3>
			<p>Si tienes alguna duda o pregunta sobre el evento, contáctanos a través de estos medios:</p>
			<div class="contacto-datos">
				<div class="contacto-dato">
					<label>Teléfonos:</label>
					<p>{{ detalles.telefono }}</p>
					<p>{{ detalles.telefono2 }}</p>
				</div>
				<div class="contacto-dato">
					<label>Correo:</label>
					<p>{{ detalles.correo }}</p>
				</div>
				
			</div>
		</div>
	</section>
</div>
{% endblock %}

django_project/blog/templates/blog/inscripcion.html
{% extends 'base/index.html' %}
{% load static %}
{% block estilos %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/inscripcion.css' %}">
{% endblock %}

{% block contenido %}

	{% if messages %}
		{% for message in messages %}
			{% if message.tags == 'warning' %}
				<h1>dscdscdscsc</h1>
				{{ participante.nombre }}
			{% endif %}
		{% endfor %}
	{% endif %}

	<div class="cont">
		<h1>Inscripción</h1>
		<label>Taller:</label>
		<p>{{taller.nombre}}</p>
		<div class="datos">
			<label>Lugares disponibles:</label>
			{% if  taller.cupo %}
				<p>{{taller.cupo}} lugares</p>
			{% else %}
			<p>0 lugares</p>
			{% endif %}
		</div>
		
		<form class="form" method="POST">
			<p>Si ya estás registrado completa los siguientes campos:</p>
			{% csrf_token %}
			{{ form.as_p }}
			<!--<label>Nombre:</label>
			<input type="text"></input>
			<label>Apellido Paterno:</label>
			<input type="text"></input>
			<label>Apellido Materno:</label>
			<input type="text"></input>
			<button type="submit">Inscribirse</button>-->
			<button type="submit">Inscribirse</button>
			<a href="{% url 'taller:tallerRegistro' %}">¿Todavía no estás registrado?</a>
		</form>
	</div>

<script type="text/javascript" src="{% static 'js/inscripcion.js' %}"></script>

{% endblock %}

django_project/blog/templates/blog/programa.html
{% extends 'base/index.html '%}
{% load static %}

{% block estilos %}
<link rel="stylesheet" type="text/css" href="{% static 'css/programa.css' %}">
{% endblock %}

{% block contenido %}

	<div class="contenedor">
		<section class="header">
			<h1>Cronograma</h1>
			<p>Itinerario para los días jueves 25 y viernes 26 de abril</p>
		</section>
		<section class="cronograma">
			<h2>Jueves 25 de abril</h2>
			<div class="tabla">
				<div class="tabla-titulos">
					<label class="horario">HORARIO</label>
					<label class="actividad">ACTIVIDAD</label>
				</div>

				{% for detalle in jueves %}					
					<div class="tabla-parrafos">
						<p class="horario">{{detalle.horario}}</p>
						<p class="actividad">{{detalle.actividad}}</p>
					</div>
				{% endfor %}
			</div>

		</section>

		<section class="cronograma">
			<h2>Viernes 26 de abril</h2>
			<div class="tabla">
				<div class="tabla-titulos">
					<label class="horario">HORARIO</label>
					<label class="actividad">ACTIVIDAD</label>
				</div>
				{% for detalle in viernes %}
					<div class="tabla-parrafos">
						<p class="horario">{{detalle.horario}}</p>
						<p class="actividad">{{detalle.actividad}}</p>
					</div>
				{% endfor %}
			</div>

		</section>
	</div>

{% endblock %}

django_project/blog/templates/blog/registro.html
{% extends 'base/index.html '%}
{% load static %}

{% block estilos %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
{% endblock %}

{% block contenido %}
<div class="cont">
	<h1>Registro</h1>
	<form class="form" method="post">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit">Registrarse</button>
	</form>
</div>
{% endblock %}

django_project/blog/templates/blog/talleres.html
{% extends 'base/index.html '%}
{% load static %}

{% block estilos %}
<link rel="stylesheet" type="text/css" href="{% static 'css/programa.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/talleres.css' %}">
{% endblock %}

{% block contenido %}
	
	<div class="contenedor">
		<section class="header">
			<h1>Talleres</h1>
		</section>
		<section class="cronograma">
			<section class="contenedor-tabla">
				<div class="infoTabla">
					<h3>Jueves 25 de abril</h3>
					<small>Talleres 12:00 - 14:30</small>
					<p>Selecciona un taller para inscribirte</p>
				</div>
				<div class="tabla">
					{% for detalle in jueves1 %}
					<div class="tabla-parrafos">
						<p class="taller">{{detalle.nombre}}</p>
						<p class="ponente">{{detalle.ponente}}</p>
						<a href="{% url 'taller:tallerInscripcion' detalle.id %}" class="accion">Inscribirme</a>
					</div>
					{% endfor %}
				</div>
			</section>
		</section>

		<section class="cronograma">
			<div class="infoTabla">
				<h3>Jueves 25 de abril</h3>
				<small>Talleres 17:10 - 19:30</small>
				<p>Selecciona un taller para inscribirte</p>
			</div>
			<section class="contenedor-tabla">
				<div class="tabla">
					{% for detalle in jueves2 %}
					<div class="tabla-parrafos">
						<p class="taller">{{detalle.nombre}}</p>
						<p class="ponente">{{detalle.ponente}}</p>
						<a href="{% url 'taller:tallerInscripcion' detalle.id %}" class="accion">Inscribirme</a>
					</div>
					{% endfor %}
				</div>
			</section>
		</section>


		<section class="cronograma">
			<section class="contenedor-tabla">
				<div class="infoTabla">
					<h3>Viernes 26 de abril</h3>
					<small>Talleres 11:00 - 13:30</small>
					<p>Selecciona un taller para inscribirte</p>
				</div>
				<div class="tabla">
					{% for detalle in viernes %}
					<div class="tabla-parrafos">
						<p class="taller">{{detalle.nombre}}</p>
						<p class="ponente">{{detalle.ponente}}</p>
						<a href="{% url 'taller:tallerInscripcion' detalle.id %}" class="accion">Inscribirme</a>
					</div>
					{% endfor %}
				</div>
			</section>
		</section>


	</div>

{% endblock %}

django_project/blog/templates/blog/warning.html
{% extends 'base/index.html '%}
{% load static %}
{% block estilos %}
<link rel="stylesheet" type="text/css" href="{% static 'css/warning.css' %}">
{% endblock%}

{% block contenido %}
<div class="contenedor">
	<section class="exito">
		{% if taller %}
			<h1>Ya estás registrado en otro taller con el mismo horario:</h1>
			<h2>{{taller}}</h2>
			<p>¿Quieres hacer el cambio de talleres?</p>
			<a href="{% url 'taller:tallerWarning' i t 1 %}" id="si">Sí</a>
			<a href="{% url 'taller:tallerTalleres' %}" id="no">No</a>
		{% else %}
			<h1>Inscripción exitosa</h1>
			<a href="{% url 'taller:tallerTalleres' %}" >Regresar</a>
		{% endif %}
	</section>
</div>

{% endblock %}